### ISSUE TITLE
Follow A User

### ISSUE THREAD

**Issue by FelicityHarvard** [Intro-to-SE-Spring-2020/Achievers#3]
As a user I want to be able to follow users so that I can see content I prefer
@aqd14

**Comment by daltonrpruitt** [comment]
### Task Breakdown:
- [ ] Complete User Home Page (HTML/CSS/etc.)
- [ ] Add "followed users" container to User Account in Database
- [ ] Add functionality for a "Follow" button, which adds another user to the current user's "followed users" list/container
- [ ] Show a user's followed users' tweets in the current user's feed

### Optional:
- [ ] Add a way for a user to see their "followed users"

**Comment by daltonrpruitt** [comment]
Acceptance Test:
1. Assuming user is signed in and sees another User they want to follow. 
2. Click on "Follow" button
3. See "Success" indication (TBD)
4. The other user appears in the current user's "Following" area
4. (Optional) The Tweets of those a user follows appear at the top of their feed or in a special "Following" section.

**Comment by CTMills** [comment]
Finished implementation of following a user

**Comment by daltonrpruitt** [comment]
Story points : 6
